wallpaper {
    monitor = eDP-1
    path = ~/projects/configs/images/lake-mountain.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/projects/configs/images/coral.jpg
    fit_mode = cover
}
